version: "3"
services:
  betterprogrammerapi:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
  mongo:
    image: mongo 
    ports:
      - "2707:2707"
    volumes: 
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local    
